# Generated by Django 4.2.1 on 2023-05-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_posts_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profileuser'),
        ),
    ]
